project:
  type: website
  output-dir: docs

website:
  title: "Zoe Ellis"
  page-footer: "© 2025 Zoe Ellis | All rights reserved."
  favicon: favicon.ico
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: ZEResume.pdf
        text: Resume
        target: _blank
      - href: resources.qmd
        text: Projects
      - href: file/path/to/myCV.pdf  # Providing a relative file path to a PDF
        text: CV
        target: _blank  # Opens link (or page) in a new browser tab
      - icon: github  # Add icons as navbar buttons
        href: https://github.com/zoellis  # Correct GitHub link format
        target: _blank
    left:
      - href: index.qmd
        text: Home
format:
  html:
    theme:
    - sketchy
    - styles.scss
    toc: true
    page-layout: full
